### ISSUE TITLE
contact section

### ISSUE THREAD

**Issue by ad3429** [SaxonScarlet/prj-rev-bwfs-tea-cozy#3]
https://github.com/SaxonScarlet/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy_V2/index.html#L91-L95

One thing I noticed is that when I decrease the browser width the contact section seems to move with it, while all of the other sections remain fixed. This is not necessarily a bad thing, but you should remain consistent just for a good user experience -- this should be a simple change in your CSS to keep this section fixed.

**Comment by SaxonScarlet** [comment]
Thank you. I shall investigate which display to use.
