### ISSUE TITLE
responsive design

### ISSUE THREAD

**Issue by ad3429** [SaxonScarlet/prj-rev-bwfs-tea-cozy#4]
https://github.com/SaxonScarlet/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy_V2/index.html#L8-L101

In the next project you will learn more about responsive design, which is really good for creating sites that look nicely on different browser sizes/platforms. Here is a great resource to get you to start thinking about this:

https://www.w3schools.com/css/css_responsive_intro.asp

**Comment by SaxonScarlet** [comment]
Understood. Thank you.
