### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [SaxonScarlet/prj-rev-bwfs-tea-cozy#5]
**Summary Grade: Satisfactory**

Great job! Your files are organized nicely, and you did a great job of matching the client specification -- this is an important skill to have as a developer and you seem to understand that. Moreover, you generally followed excellent code practice, so make sure to keep that up!

I have made some comments in your code to take note of. Great job commenting the main parts of your HTML -- this will greatly help you as your projects get more complex since it saves a lot of time when you come back to look at your code. You should also try to comment your CSS files so you know exactly why you decided to style something a particular way. I also made some comments about the contact section in your comments that you can read about. Moreover, you will learn more about this in the future so I wouldn't worry too much about it now, but here is a great resource on responsive web design which will teach you to build sites that look and act good on different browser sizes/platforms:

https://www.w3schools.com/css/css_responsive_intro.asp

Great job overall! As a further challenge, try using css to design your webpage even further! You did a great job in following the client specification, but for your own practice you should see how creative you can get by taking the design/styling of your site to the next level (for example, you can try experimenting with background colors on your other divs)

**Comment by SaxonScarlet** [comment]
Thank you for the review.

I shall apply your advice to future projects.
(I'll retry this exercise at a later stage)
